config/routes.rb
Greek::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations", :omniauth_callbacks => "omniauth_callbacks" }

  authenticated :user do
    root :to => "pages#index"
  end

  get 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite

  scope "/admin" do
    resources :users, :only => [:index, :new] do
      collection { post :import }
      get 'invite', :on => :member
      # resources :import_s, :only => :create
    end
  end

  scope "/official" do
    resources :approvals
    post ':approvals/new' => 'approvals#create', :as => :create_approval
  end

  scope "/officer" do
    resources :chapters, :only => [:show, :edit]
  end

  resources :organizations do
    resources :chapters
  end
  resources :chapters
  resources :schools
  resources :volunteerings
  resources :donations
  resources :blogs

  as :user do
    get 'request-invite', to: 'devise/registrations#new', :via => :post, :as => :invite
    get 'login',    to: 'devise/sessions#new',      :as => :login
    # get 'user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    put 'user/confirmation' => 'confirmations#update', :as => :update_user_confirmation
    get 'account', to: 'devise/registrations#edit', :as => :account
    delete 'logout' => 'devise/sessions#destroy',  :as => :logout
  end

  get 'auth/:provider/callback', to: 'devise/sessions#create'
  get 'auth/failure', to: redirect('/')

  get "home"  => 'pages#index', as: :home
  get "about" => 'pages#about', as: :about
  get "feed"  => 'pages#feed',  as: :feed

  root :to => "pages#index"

  # get '/registration', to: 'users#registration'
  # put '/registration', to: 'users#update'
  get 'users/:id', to: 'profiles#show', as: :profile
  get 'profiles/:id', to: 'profiles#show', as: :profile
  get 'thanks', to: 'pages#thanks'#, as: :thanks

  match '*path' => redirect('/'), via: :get
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = UserDecorator.find(params[:id]) rescue nil
  	if !@user._official?
  		donations = @user.donations
  		volunteerings = @user.volunteerings
  		blogs = @user.blogs
      approvals = @user.approvals.sort_by(&:created_at).reverse
      @feed = (donations + volunteerings + blogs + approvals).sort_by(&:created_at).reverse
  		render action: :show
  	elsif @user._official?
      @feed = @user.approvals.sort_by(&:created_at).reverse
    else
      redirect_to root_path, notice: "Sorry, could not locate that user."
	  end
  end
end

app/views/profiles/_profile_feed.html.haml
-unless @user.is_administrator?
  %th{:style => "text-align:center;"}
    %span=current_user == @user ? "Your Recent Activity" : "#{@user.first_name}'s Recent Activity"
-else
  %th{:style => "text-align:center;"}="#{@user.first_name}'s Recent Approvals"

-if @feed.present?
  -@feed.each do |feed|
    -if feed[:value]
      %tr
        %td{:style => "text-align:center"}
          %span.label.pull-left Donation
          %strong=link_to number_to_currency(feed.value), feed
          %span.label.label-success raised
          %span="#{time_ago_in_words(feed.created_at)} ago."

    -elsif feed[:hours]
      %tr
        %td{:style => "text-align:center"}
          %span.label.pull-left Volunteering
          %strong=link_to "#{feed.hours} hours", feed
          %span.label.label-important volunteered
          %span="#{time_ago_in_words(feed.created_at)} ago."
    -elsif feed.class == Blog
      %tr
        %td{:style => "text-align:center"}
          %span.label.pull-left Blog
          %strong=link_to truncate(feed.title, :length => 35), feed
          %span.label.label-info posted
          %span="#{time_ago_in_words(feed.created_at)} ago"

    -elsif feed.approvable.class == Donation
      %tr
        %td{:style => "text-align:center"}
          %span.pull-left
            %span.label Approval
            %span.label.label-success Donation
          %strong=link_to truncate(feed.approvable.title, :length => 28), feed.approvable
          %span.label.label-success approved
          %span="#{time_ago_in_words(feed.created_at)} ago."
    -elsif feed.approvable.class == Volunteering
      %tr
        %td{:style => "text-align:center"}
          %span.pull-left
            %span.label Approval
            %span.label.label-warning Volunteering
          %strong=link_to truncate(feed.approvable.title, :length => 28), feed.approvable
          %span.label.label-success approved
          %span="#{time_ago_in_words(feed.created_at)} ago."

-else
  %tr
    %td.empty-table
      %span=link_to raw("None! Review activity now &rarr;"), approvals_path, :class => "btn btn-large btn-danger"

app/views/profiles/_profile_sidebar.html.haml
.span4
  %div.well
    -unless @user._official? # org, chapter-related stats (official doesn't have these).
      %h5.inline="#{@user.member_type.titleize},"
      %h5.inline=link_to truncate(@user.chapter.name, :length => 20), @user.chapter
      %small chapter.
      %span
        %small.subtitle=@user.role
      %p
        %small=@user.chapter_raised_total
      %p
        %small=@user.chapter_hours_total
      %h5.inline=link_to truncate(@user.organization.name, :length => 20), @user.organization
      %span
        %small.subtitle=@user.org_legitimacy_ratio
      %p
        %small=@user.org_raised_total
      %p
        %small=@user.org_hours_total

    %h6.inline=link_to truncate(@user.school.name, :length => 28), @user.school
    %span
      %small.subtitle=@user.school_legitimacy_ratio
    %p
      %strong=@user.school.location
    %p
      %small=@user.school_raised_total
    %p
      %small=@user.school_hours_total

  -if !@user._official?
    .row-fluid
      .span12.well
        %div
          %p
            %strong Personal Statistics:
          %span=@user.total_raised # personal total
          %p
            %small.subtitle=@user.percentage_of_chapter_funds
        %div
          %span=@user.total_hours  # personal total
          %p
            %small.subtitle=@user.percentage_of_chapter_hours
  -elsif @user._official?
    .row-fluid
      .span12.well
        %p=@user.total_activities
        %p=@user.total_approved
        %p=@user.unapproved_donations
        %p=@user.unapproved_volunteerings
        %p=@user.legitimacy_ratio

  -if current_user
    -if current_user == @user
      %div.well.text-center.padding-20
        %h6 Activity Console
        %ul.unstyled.inline
          -unless @user._official?
            %li=link_to "Post Donations", donations_path,         :class => "btn btn-mini btn-success"
            %li=link_to "Post Volunteerings", volunteerings_path, :class => "btn btn-mini btn-danger"
          %li=link_to "New Blog", blogs_path,                     :class => "btn btn-mini btn-info"

app/views/profiles/show.html.haml
.row-fluid
  .span10.offset1
    .row-fluid.margin-top-25
      %span.gravatar=image_tag(@user.gravatar_url)
      %h2.inline=@user.full_name
      %span.pull-right.margin-top-25=link_to raw("&larr; Back").html_safe, :back, :class => "btn btn-mini"
      %span.edit.subtitle=current_user == @user ? (link_to "Edit", account_path if current_user == @user) : @user.role_title

    .row-fluid
      =render "profile_sidebar"

      .span8
        %table.table.table-bordered.table-striped
          %tr
            =render "profile_feed"