config/routes.rb
Greek::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations", :omniauth_callbacks => "omniauth_callbacks" }

  authenticated :user do
    root :to => "pages#index"
  end

  get 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite

  scope "/admin" do
    resources :users, :only => [:index, :new] do
      collection { post :import }
      get 'invite', :on => :member
      # resources :import_s, :only => :create
    end
  end

  scope "/official" do
    resources :approvals
    post ':approvals/new' => 'approvals#create', :as => :create_approval
  end

  scope "/officer" do
    resources :chapters, :only => [:show, :edit]
  end

  resources :organizations do
    resources :chapters
  end
  resources :chapters
  resources :schools
  resources :volunteerings
  resources :donations
  resources :blogs

  as :user do
    get 'request-invite', to: 'devise/registrations#new', :via => :post, :as => :invite
    get 'login',    to: 'devise/sessions#new',      :as => :login
    # get 'user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    put 'user/confirmation' => 'confirmations#update', :as => :update_user_confirmation
    get 'account', to: 'devise/registrations#edit', :as => :account
    delete 'logout' => 'devise/sessions#destroy',  :as => :logout
  end

  get 'auth/:provider/callback', to: 'devise/sessions#create'
  get 'auth/failure', to: redirect('/')

  get "home"  => 'pages#index', as: :home
  get "about" => 'pages#about', as: :about
  get "feed"  => 'pages#feed',  as: :feed

  root :to => "pages#index"

  # get '/registration', to: 'users#registration'
  # put '/registration', to: 'users#update'
  get 'users/:id', to: 'profiles#show', as: :profile
  get 'profiles/:id', to: 'profiles#show', as: :profile
  get 'thanks', to: 'pages#thanks'#, as: :thanks

  match '*path' => redirect('/'), via: :get
end

app/models/volunteering.rb
class Volunteering < ActiveRecord::Base
  attr_accessible :beneficiary, :hours, :location, :purpose, :sponsor, :title, :longitude, :latitude, :user, :date, :school_id, :school

  scope :approved, where(:approved => true)
  scope :unapproved, where(:approved => false)

  has_one :approval, :as => :approvable, :dependent => :destroy
  belongs_to :user

  geocoded_by :location
    after_validation :geocode, :if => :location_changed?

  def approved?
    !!self.approval
  end

  def self.approved
    self.all.map(&:approved?).keep_if {|d| d==true}.size
  end

  def self.unapproved
    self.all.map(&:approved?).keep_if {|d| d==false}.size
  end

  def date
    self.created_at
  end

  def to_param
    [id, title.parameterize].join('-')
  end
end

app/controllers/volunteerings_controller.rb
class VolunteeringsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

   def index
    @volunteerings = Volunteering.order('created_at DESC')
  end

  def new
    @volunteering = Volunteering.new
  end

  def show
    @volunteering = Volunteering.find(params[:id]).decorate

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @volunteering }
    end
  end

  def edit
    @volunteering = Volunteering.find(params[:id])
  end

  def create
    @user = User.find(current_user.id)
    @volunteering = @user.volunteerings.new(params[:volunteering])
    @volunteering.school_id = @user.school.id

    respond_to do |format|
      if @volunteering.save
        format.html { redirect_to volunteerings_path, notice: 'Volunteering was successfully created.' }
        format.json { render json: @volunteering, status: :created, location: @volunteering }
      else
        format.html { render action: "new" }
        format.json { render json: @volunteering.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @volunteering = Volunteering.find(params[:id])

    respond_to do |format|
      if @volunteering.update_attributes(params[:volunteering])
        format.html { redirect_to @volunteering, notice: 'Volunteering was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @volunteering.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @volunteering = Volunteering.find(params[:id])
    @volunteering.destroy

    respond_to do |format|
      format.html { redirect_to volunteerings_url }
      format.json { head :no_content }
    end
  end
end

app/views/volunteerings/_author.html.haml
.span6.offset3.well.text-center
  %small
    Time volunteered by
    %strong=link_to "#{@volunteering.user.name},", profile_path(@volunteering.user.id)
    a
    %span=@volunteering.user.gender
    %br
    of the
    %strong=link_to "#{@volunteering.user.chapter.name}", @volunteering.user.chapter, :title => raw("#{@volunteering.user.chapter.name.titleize} Chapter activity &rarr;").html_safe
    chapter of
    %strong=link_to @volunteering.user.organization.name, @volunteering.user.organization, :title => raw("#{@volunteering.user.organization.name.titleize} #{@volunteering.user.organization.gender.titleize} at #{@volunteering.user.school.name.titleize} &rarr;").html_safe
    at
    the
    %strong=link_to @volunteering.user.school.name, @volunteering.user.school, :title => raw("Greek-life activity at #{@volunteering.user.school.name.titleize} &rarr;").html_safe

app/views/volunteerings/_form.html.haml
=simple_form_for @volunteering do |f|
  -if @volunteering.errors.any?
    #error_explanation
      %h2= "#{pluralize(@volunteering.errors.count, "error")} prohibited this volunteering from being saved:"
      %ul
        -@volunteering.errors.full_messages.each do |msg|
          %li= msg
  %br
  .field=f.text_field :hours, :placeholder => "Hours Volunteered"
  .field=f.text_field :beneficiary, :placeholder => "Beneficiary Name"
  .field=f.text_field :title, :placeholder => "Project Title"
  .field=f.text_field :location, :placeholder => "Location (Volunteering)"
  .field=f.text_field :sponsor, :placeholder => "Sponsor"
  .field=f.text_area :purpose, :placeholder => "Purpose of Volunteering"
  .field=f.submit 'Document', class: "btn btn-success btn-large"

app/views/volunteerings/edit.html.haml
%h1 Editing volunteering

= render 'form'

= link_to 'Show', @volunteering
\|
= link_to 'Back', volunteerings_path

app/views/volunteerings/index.html.haml
.row-fluid
  .span10.offset1.margin-top-25
    %h2.inline Volunteerings

    -unless !current_user or current_user._official?
      %span.pull-right.margin-control-15=link_to raw("Document Volunteer Hours &rarr;").html_safe, new_volunteering_path, :class => "btn btn-success btn-large"
    -else
      %span.pull-right.margin-top-25=link_to raw("&larr; Back").html_safe, :back, :class => "btn btn-mini"

    %table.table.table-bordered.table-striped
      %tr
        %th Hours
        %th Title
        %th Beneficiary
        %th Location
        %th Purpose
        %th Sponsor
        -if current_user
          -if current_user.volunteerings.present?
            %th{colspan: 2} Manage

      -if current_user
        -if current_user.volunteerings.present?
          -current_user.volunteerings.each do |volunteering|
            %tr
              %td= volunteering.hours
              %td= link_to volunteering.title, volunteering
              %td= truncate(volunteering.beneficiary, :length => 20)
              %td= truncate(volunteering.location, :length => 20)
              %td= truncate(volunteering.purpose, :length => 20)
              %td= volunteering.sponsor
              -if is_owner?(volunteering)
                %td= link_to 'Edit', edit_volunteering_path(volunteering)
                %td= link_to 'Delete', volunteering, :method => :delete, :data => { :confirm => 'Are you sure?' }
        -elsif current_user._official?
          %th.empty-table{colspan: 6}
            %span No recent activity!

      -else
        %th.empty-table{colspan: 6}
          %span No recent activity!
          %span.margin-sides-5 Get started:
          %span=link_to "Request Invite", register_path, :class => "btn btn-success btn-mini margin-sides-5"
          %span=link_to "Log In", login_path, :class => "btn btn-info btn-mini margin-sides-5"

    .row-fluid.text-center
      %span=link_to raw('&larr; Back').html_safe, :back

app/views/volunteerings/new.html.haml
.row-fluid.margin-top-50.text-center
  .span6.offset3.well
    %h1 New Volunteering
    =render 'form'
.row-fluid
  .span6.offset3.well.text-center
    =link_to raw('&larr; Back').html_safe, volunteerings_path

app/views/volunteerings/show.html.haml
-content_for :head do
  %head{:prefix => "og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# greekgood: http://ogp.me/ns/fb/greekgood#"}
    %meta{:content => ENV['APP_ID'], :property => "fb:app_id"}/
    %meta{:content => "greekgood:dollar", :property => "og:type"}/
    %meta{:content => volunteering_url(@volunteering), :property => "og:url"}/
    %meta{:content => @volunteering.hours, :property => "og:title"}/
    %meta{:content => "https://fbstatic-a.akamaihd.net/images/devsite/attachment_blank.png", :property => "og:image"}/

.row-fluid
  .span6.offset3.panel.text-center.margin-top-50
    %h4.page-header=@volunteering.title.titleize
    %p
      %b Hours Volunteered:
      =@volunteering.hours

    %strong Beneficiary:
    .label=@volunteering.beneficiary

    %p
    %p
      %b Location:
      =@volunteering.location
    %p
      %b Purpose:
      =@volunteering.purpose
    %p
      %b Sponsor:
      =@volunteering.sponsor

    .label{ :class => @volunteering.label_class }=@volunteering.status

.row-fluid
  =render "author"

-if current_user
  .row-fluid
    .span6.offset3.text-center.margin-0.padding-5
      %ul.manage-links
        %li=link_to raw('&larr; Back').html_safe, :back
        -if !@volunteering.approved?
          -if current_user.can_approve?(@volunteering)
            \|
            %li=button_to 'Approve', { controller: "approvals", action: "create", id: @volunteering.id, approvable_type: "volunteering" }, :class => "btn btn-mini btn-success"
        -elsif is_owner?(@volunteering.approval)        # did you approve originally?
          \|
          %li=link_to 'Unapprove', @volunteering.approval, :class=> "btn btn-mini btn-danger", method: :delete, :data => { :confirm => "Really Unapprove?" }
        -elsif (is_owner?(@volunteering) || current_user.has_role?(:admin))
          \|
          %li=link_to 'Edit', edit_volunteering_path(@volunteering), :class=> "btn btn-mini"

-else
  .row-fluid.text-center
    %span=link_to raw('&larr; Back').html_safe, :back