config/routes.rb
Greek::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations", :omniauth_callbacks => "omniauth_callbacks" }

  authenticated :user do
    root :to => "pages#index"
  end

  get 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite

  scope "/admin" do
    resources :users, :only => [:index, :new] do
      collection { post :import }
      get 'invite', :on => :member
      # resources :import_s, :only => :create
    end
  end

  scope "/official" do
    resources :approvals
    post ':approvals/new' => 'approvals#create', :as => :create_approval
  end

  scope "/officer" do
    resources :chapters, :only => [:show, :edit]
  end

  resources :organizations do
    resources :chapters
  end
  resources :chapters
  resources :schools
  resources :volunteerings
  resources :donations
  resources :blogs

  as :user do
    get 'request-invite', to: 'devise/registrations#new', :via => :post, :as => :invite
    get 'login',    to: 'devise/sessions#new',      :as => :login
    # get 'user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    put 'user/confirmation' => 'confirmations#update', :as => :update_user_confirmation
    get 'account', to: 'devise/registrations#edit', :as => :account
    delete 'logout' => 'devise/sessions#destroy',  :as => :logout
  end

  get 'auth/:provider/callback', to: 'devise/sessions#create'
  get 'auth/failure', to: redirect('/')

  get "home"  => 'pages#index', as: :home
  get "about" => 'pages#about', as: :about
  get "feed"  => 'pages#feed',  as: :feed

  root :to => "pages#index"

  # get '/registration', to: 'users#registration'
  # put '/registration', to: 'users#update'
  get 'users/:id', to: 'profiles#show', as: :profile
  get 'profiles/:id', to: 'profiles#show', as: :profile
  get 'thanks', to: 'pages#thanks'#, as: :thanks

  match '*path' => redirect('/'), via: :get
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :role_ids, :as => :admin
  attr_accessible :oauth_expires_at, :name, :email,
                  :oauth_token, :provider, :uid,
                  :organization, :organization_id,
                  :chapter, :chapter_id, :school,
                  :school_id, :first_name, :last_name,
                  :password, :password_confirmation,
                  :remember_me, :confirmed_at#, :profile_name

  belongs_to :organization
  belongs_to :chapter
  belongs_to :school

  has_many :donations, :dependent => :destroy
  has_many :volunteerings, :dependent => :destroy
  has_many :blogs, :dependent => :destroy
  has_many :approvals, :dependent => :destroy

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true
  validates :school, :presence => true

  # need a default scope ordered by value of donations. Descending.

  mount_uploader :image, ImageUploader
  # mount_uploader :csv, CsvUploader

  # after_create :add_profile_name
  # has_and_belongs_to_many :roles, :join_table => :users_roles

  # after_create :add_user_to_mailchimp
  # before_destroy :remove_user_from_mailchimp

  after_create :assign_role
  # after_create :add_name

  # override Devise method
  # no password is required when the account is created; validate password when the user sets one
  # validates_confirmation_of :password
  def to_param
    [id, name.parameterize].join('-') unless self.name.nil?
  end

  def password_required?
    if !persisted?
      !(password != "")
    else
      !password.nil? || !password_confirmation.nil?
    end
  end

  def _official?
    self.chapter.blank? || (self.organization.blank? && self.has_role?(:official))
  end

  def is_administrator?
    self.has_role? :admin or self.has_role? :official
  end

  def can_approve?(resource)
    self.has_role? :official and self.school.id == resource.school_id
  end

  def is_official?
    self.has_role? :official
  end

  def superuser?
    self.has_role? :admin and self.has_role? :official
  end

  def is_officer?
    self.has_role? :officer
  end

  def chapter_brother?(chapter)
    self.chapter == chapter
  end

  def chapter_officer?(chapter)
    chapter_brother?(chapter) && (self.is_officer? || self.has_role?(:admin))
  end

  def can_edit_chapter?(chapter)
    chapter_officer?(chapter) || self.superuser?
  end

  def can_edit_organization?
    self.superuser?
  end

  def gender
    self.organization.gender.blank? ? "member" : member_type
  end

  def member_type
    self.organization.gender.downcase == "fraternity" ? "brother" : "sister"
  end

  def sum_donations
    self.donations.sum(:value)
  end

  def sum_volunteerings
    self.volunteerings.sum(:hours)
  end

  # override Devise method
  def confirmation_required?
    false
  end

  # override Devise method
  def active_for_authentication?
    confirmed? || confirmation_period_valid?
  end

  def send_reset_password_instructions
    if self.confirmed?
      super
    else
      errors.add :base, "You must receive an invitation before you set your password."
    end
  end

  # new function to set the password
  def attempt_set_password(params)
    p = {}
    p[:password] = params[:password]
    p[:password_confirmation] = params[:password_confirmation]
    update_attributes(p)
  end

  # new function to determine whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  # new function to provide access to protected method pending_any_confirmation
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def profile_name
    self.last_name.downcase
  end

  def gravatar_url
    email = self.email.strip.downcase
    # downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(email)
    "http://gravatar.com/avatar/#{hash}"
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid, :email)).first_or_initialize.tap do |user|
      user.provider         = auth.provider
      user.uid              = auth.uid
      user.name             = auth.info.name
      user.username         = auth.info.username
      user.image            = auth.info.image
      user.oauth_token      = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def registration_complete? # false if nil.
    !self.organization.nil? || !self.chapter.nil? || !self.school.nil?
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
    block_given? ? yield(@facebook) : @facebook
  rescue Koala::Facebook::APIError => e
    logger.info e.to_s
    nil
  end

  class << self
    def import(file)
      # begin
        # spreadsheet = open_spreadsheet(file)
        # header = spreadsheet(row[1])
        CSV.foreach(file, :headers => true) do |row|
          u = User.new
          u.update_attributes!({
            :organization => Organization.find_or_create_by_name(row[0]),
            :chapter    => Organization.find_or_create_by_name(row[1]),
            :school     => School.find_or_create_by_name(row[2]),
            :email      => row[3],
            :first_name => row[4],
            :last_name  => row[5]
          })
        end
      # rescue
      #   "ERROR!"
      # end
    end
  end

  private

  def add_name
  end

  def assign_role
    self.add_role :user if self.roles.first.nil?
  end

  def remove_role(role, *args)
    target = args.first.presence

    #target is nil when appropriate
    role = Role.where(:name => role, :member_id => self.id, :rollable => target).first
    role.delete
  end

  # def add_profile_name
    # self.profile_name = self.username.downcase.strip
    # User.pluck(:last_name).lowercase = self.profile_name
  # end

  #  def add_user_to_mailchimp
  #   return if email.include?(ENV['ADMIN_EMAIL'])
  #   mailchimp = Gibbon.new
  #   result = mailchimp.list_subscribe({
  #     :id => ENV['MAILCHIMP_LIST_ID'],
  #     :email_address => self.email,
  #     :double_optin => false,
  #     :update_existing => true,
  #     :send_welcome => true
  #     })
  #   Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  # rescue Gibbon::MailChimpError => e
  #   Rails.logger.info("MailChimp subscribe failed for #{self.email}: " + e.message)
  # end

  # def remove_user_from_mailchimp
  #   mailchimp = Gibbon.new
  #   result = mailchimp.list_unsubscribe({
  #     :id => ENV['MAILCHIMP_LIST_ID'],
  #     :email_address => self.email,
  #     :delete_member => true,
  #     :send_goodbye => false,
  #     :send_notify => true
  #     })
  #   Rails.logger.info("Unsubscribed #{self.email} from MailChimp") if result
  # rescue Gibbon::MailChimpError => e
  #   Rails.logger.info("MailChimp unsubscribe failed for #{self.email}: " + e.message)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def new
    user = User.from_omniauth(env["omniauth.auth"])
    @schools = School.order('name')
    @roles = Role.order('name')
    # @user = User.new
  end

  def create
    @user = User.new params[:user]
    @user.school_id = params[:school]
    @user.roles << Role.find(params[:role])

    if @user.save
      Rails.logger.info "#{@user.full_name}, #{@user.roles.first.name} created."
      redirect_to users_path, :notice => "#{@user.first_name} successfully created."
    else
      render :new, :flash => { :error => "Sorry, experienced an error." }
    end
  end

	# def update
	# 	@user = current_user
	# 	@user.update_attributes(params[:user])
	# 	if @user.save
	# 		redirect_to root_url, :flash => { :success => "Thanks, for joining. Time to change the world." }
	# 	else
	# 		render 'registration', flash[:error] = "Sorry, could not update details."
	# 	end
	# end

	def show
    @user = User.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  def invite
    authorize! :invite, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    @user.send_confirmation_instructions
    redirect_to :back, :only_path => true, :notice => "Sent invitation to #{@user.email}."
  end

  def bulk_invite
    authorize! :bulk_invite, @user, :message => 'Not authorized as an administrator.'
    users = User.where(:confirmation_token => nil).order(:created_at).limit(params[:quantity])
    count = users.count
    users.each do |user|
      user.send_confirmation_instructions
    end
    redirect_to :back, :only_path => true, :notice => "Sent invitation to #{count} users."
  end

  def import
    User.import(params[:file])
    redirect_to users_path, :notice => "Users successfully imported."
  end
end

app/views/users/_admin_form.haml
-if current_user.has_role? :admin
  =simple_form_for(@user, :url => url_for(:controller => 'users', :action => 'create')) do |f|
    -if @user.errors.any?
      #error_explanation
        %h6= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %ul
          -@user.errors.full_messages.each do |msg|
            %li= msg
    %br
    .field=f.text_field :first_name, :placeholder => "First name"
    .field=f.text_field :last_name, :placeholder => "Last name"
    .field=f.text_field :email, :placeholder => "Email"
    .field=select_tag "school", options_from_collection_for_select(@schools, "id", "name")
    .field=select_tag "role", options_from_collection_for_select(@roles, "id", "name")
    .actions=f.button :submit, 'Create', :class => "btn btn-success btn-large"
-else
  %span.text-center Not authorized.

app/views/users/_form.haml
=simple_form_for(:user, :url => url_for(:controller => 'users', :action => 'update')) do |f|
  .field=f.select(:school_id, options_from_collection_for_select(@schools, :id, :name), prompt: "Select Your School")
  .field=f.select(:organization_id, options_from_collection_for_select(@organizations, :id, :name), prompt: "Select Your Organization")
  .field=f.select(:chapter_id, options_from_collection_for_select(@chapters, :id, :name), prompt: "Select Your Chapter")
  .actions=f.button :submit, "Register", class: "btn btn-success"

app/views/users/_import.html.haml
.modal{:id => "import-users", :style => "display: none;"}
  =form_tag import_users_path, multi_part: true do
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Bulk-Import Users Coming Soon.
    .modal-body
      %p Formatting guidelines:
      %ul
        %li
          %strong Organization name (column a):
          %span user's fraternity or sorority name.
        %li
          %strong Chapter name (column b):
          %span user's fraternity or sorority chapter's name.
        %li
          %strong School name (column c):
          %span user's school's name.
        %li
          %strong E-mail (column d):
          %span user's email.
        %li
          %strong First Name (column e):
          %span user's first name.
        %li
          %strong Last Name (column f):
          %span user's last name.

      .field=file_field_tag :file
    .modal-footer
      =submit_tag "Import", :class => "btn btn-success"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/_user.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  =simple_form_for user, :url => user_path(user.id), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      =f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      =f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/edit.haml
.row-fluid{style: "text-align:center"}
  .span6.offset3.well
    %span Hello
    %span=current_user.name
    %p Please finish your registration.
    %hr
    =render 'form'

app/views/users/index.html.haml
.span10.offset1
  %div.page-header
    %h3.inline Administration Dashboard
    %span
      %small.subtitle User Management
    %span.pull-right.margin-side-5=link_to raw("Create User " "<i class='icon-plus-sign'></i>").html_safe, new_user_path, :class => "btn btn-success"
    %span.pull-right.margin-top-20
      %a.btn{"data-toggle" => "modal", :href => "#import-users", :type => "button"} Import
      =render :partial => "import"
  %p
    Send Bulk Invitations:
    \#{link_to "10 &#183;".html_safe, bulk_invite_path(:quantity => '10')}
    \#{link_to "50 &#183;".html_safe, bulk_invite_path(:quantity => '50')}
    \#{link_to "100 &#183;".html_safe, bulk_invite_path(:quantity => '100')}
    \#{link_to "500 &#183;".html_safe, bulk_invite_path(:quantity => '500')}
    \#{link_to "1000", bulk_invite_path(:quantity => '1000')}
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Requested
        %th Invitation
        %th Joined
        %th Visits
        %th Most Recent
        %th Role
        %th
        %th
    %tbody
      -@users.each do |user|
        %tr
          %td=link_to user.full_name, profile_path(user.id)
          %td=user.email
          %td=user.created_at.to_date
          %td=(user.confirmation_token.nil? ? (link_to "Send Invitation", invite_user_path(user.id), {:class => 'btn btn-mini'}) : (link_to "resend", invite_user_path(user.id), {:class => 'btn btn-mini'})) unless user.confirmed_at
          %td=user.confirmed_at.to_date if user.confirmed_at
          %td=user.sign_in_count if user.sign_in_count
          %td=user.last_sign_in_at.to_date if user.last_sign_in_at
          %td=user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            =render user
          %td=link_to("Delete user", user_path(user.id), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/new.html.haml
.row-fluid.margin-top-50.text-center
  .span6.offset3.well
    %h1.inline Create New User
    %p
      %small.subtitle Administration Panel
    =render 'admin_form'
.row-fluid
  .span6.offset3.text-center
    =link_to raw('&larr; Back').html_safe, :back

app/views/users/show.html.haml
%h3 User
%p
  User:
%p=@user.name
%p=@user.full_name
%p=@user.first_name
%p=@user.last_name
%p
  Email:
  =@user.email if @user.email
%p=@user.inspect