config/routes.rb
Greek::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations", :omniauth_callbacks => "omniauth_callbacks" }

  authenticated :user do
    root :to => "pages#index"
  end

  get 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite

  scope "/admin" do
    resources :users, :only => [:index, :new] do
      collection { post :import }
      get 'invite', :on => :member
      # resources :import_s, :only => :create
    end
  end

  scope "/official" do
    resources :approvals
    post ':approvals/new' => 'approvals#create', :as => :create_approval
  end

  scope "/officer" do
    resources :chapters, :only => [:show, :edit]
  end

  resources :organizations do
    resources :chapters
  end
  resources :chapters
  resources :schools
  resources :volunteerings
  resources :donations
  resources :blogs

  as :user do
    get 'request-invite', to: 'devise/registrations#new', :via => :post, :as => :invite
    get 'login',    to: 'devise/sessions#new',      :as => :login
    # get 'user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
    put 'user/confirmation' => 'confirmations#update', :as => :update_user_confirmation
    get 'account', to: 'devise/registrations#edit', :as => :account
    delete 'logout' => 'devise/sessions#destroy',  :as => :logout
  end

  get 'auth/:provider/callback', to: 'devise/sessions#create'
  get 'auth/failure', to: redirect('/')

  get "home"  => 'pages#index', as: :home
  get "about" => 'pages#about', as: :about
  get "feed"  => 'pages#feed',  as: :feed

  root :to => "pages#index"

  # get '/registration', to: 'users#registration'
  # put '/registration', to: 'users#update'
  get 'users/:id', to: 'profiles#show', as: :profile
  get 'profiles/:id', to: 'profiles#show', as: :profile
  get 'thanks', to: 'pages#thanks'#, as: :thanks

  match '*path' => redirect('/'), via: :get
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  attr_accessible :mission, :name, :school, :organization, :location, :longitude, :latitude



  geocoded_by :location
  after_validation :geocode, :if => :location_changed?

  belongs_to :organization
  belongs_to :school
  has_many :users
  has_many :donations, :through => :users
  has_many :volunteerings, :through => :users
  has_many :blogs, :through => :users

  def approvals
    self.donations + self.volunteerings
  end

  def legitimacy_ratio
    self.approvals.present? ? (approved_activities.to_f / sum_activities.to_f)*100 : 0
  end

  def sum_activities
    self.donations.size + self.volunteerings.size
  end

  def approved_activities
    self.approved_volunteerings + self.approved_donations
  end

  def approved_volunteerings
    self.volunteerings.approved
  end

  def approved_donations
    self.donations.approved
  end

  def sum_donations
  	self.donations.sum(:value)
  end

  def sum_volunteerings
  	self.volunteerings.sum(:hours)
  end

  def sum_members
    self.users.size
  end

  def to_param
    [id, name.parameterize].join('-')
  end

  def average_donations
    self.donations.present? ? (self.sum_donations.to_f / sum_members.to_f) : 0
  end

  def average_volunteerings
    self.volunteerings.present? ? (self.sum_volunteerings.to_f / sum_members.to_f) : 0
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @organizations = Organization.all.sort_by(&:sum_donations).reverse
    @chapters = Chapter.all.sort_by(&:sum_donations).reverse
  end

  def show
    @chapter = Chapter.find(params[:id]).decorate
    donations = @chapter.donations.order('created_at desc')
    volunteerings = @chapter.volunteerings.order('created_at desc')
    blogs = @chapter.blogs.order('created_at desc')
    @feed = (blogs + donations + volunteerings).sort_by { |f| f.created_at }.reverse
  end

  def new
    @chapter = Chapter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chapter }
    end
  end

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def create
    # @user = User.find(current_user.id)
    @organization = Organization.find(params[:organization_id])
    @chapter = @organization.chapters.new(params[:chapter])

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render json: @chapter, status: :created, location: @chapter }
      else
        format.html { render action: "new" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @chapter = Chapter.find(params[:id])

    respond_to do |format|
      if @chapter.update_attributes(params[:chapter])
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to chapters_url }
      format.json { head :no_content }
    end
  end
end

app/views/chapters/_chapter_content.html.haml
.span9.feed
  %table.table.table-striped.table-bordered
    %tr
      %th{:style => "text-align:center"} Recent Chapter Activity
      =render "chapter_profile_feed"

.span9.user-roster
  %table.table.table-striped.table-bordered
    %tr
      %th{:style => "text-align:center", :colspan => 3} Chapter Roster
      =render "chapter_users"

app/views/chapters/_chapter_nav.html.haml
-if current_user
  -if current_user.can_edit_chapter?(@chapter)
    %ul.unstyled.inline.margin-top-25.pull-right.li-5
      %li=link_to raw("&larr; Back").html_safe, :back, :class => "btn btn-mini"
      %li=link_to 'Activity', "#", :class => "btn btn-mini btn-info hide-user"
      %li=link_to 'Users', "#", :class => "btn btn-mini btn-success hide-feed"
      %li=link_to 'Edit', edit_chapter_path(@chapter), :class => "btn btn-mini btn-warning"
-else
  %span.pull-right.margin-top-25=link_to raw("&larr; Back").html_safe, :back, :class => "btn btn-mini"

app/views/chapters/_chapter_profile_feed.html.haml
-if @feed.present?
  -@feed.each do |feed|
    -if feed[:value]
      %tr
        %td{:style => "text-align:center"}
          %span.label.pull-left Donation
          %strong=link_to feed.user.name, profile_path(feed.user.id)
          %span.label.label-success raised
          %strong=link_to number_to_currency(feed.value), feed
          %span="#{time_ago_in_words(feed.created_at)} ago."

    -elsif feed[:hours]
      %tr
        %td{:style => "text-align:center"}
          %span.label.pull-left Volunteering
          %strong=link_to feed.user.name, profile_path(feed.user.id)
          %span.label.label-important volunteered
          %strong=link_to "#{feed.hours} hours", feed
          %span="#{time_ago_in_words(feed.created_at)} ago."
    -elsif feed.class == Blog
      %tr
        %td{:style => "text-align:center"}
          %span.label.pull-left Blog
          %strong=link_to feed.user.name, profile_path(feed.user.id)
          %span.label.label-info posted
          %strong=link_to truncate(feed.title, :length => 35), feed
          %span="#{time_ago_in_words(feed.created_at)} ago"

-else
  %tr
    %td.empty-table
      / %th.empty-table{colspan: 6}
      -unless current_user.is_administrator?
        %span No recent activity!
        %span.margin-sides-5 Get started:
        %span=link_to "Request Invite", register_path, :class => "btn btn-success btn-mini margin-sides-5"
        %span=link_to "Log In", login_path, :class => "btn btn-info btn-mini margin-sides-5"
      -else
        %span No recent activity!

app/views/chapters/_chapter_sidebar.html.haml
.span3
  %div.well
    %h5.inline=link_to truncate(@chapter.organization.name, :length => 25), @chapter.organization
    %span
      %small.subtitle=@chapter.organization.gender
    %p
      %strong School:
      %span=link_to truncate(@chapter.school.name, :length => 25), @chapter.school
    %p
      %strong Members:
      %span=@chapter.sum_members

  .row-fluid
    .span12.well
      %p
        %strong Total raised to date:
        %span.label.label-success=@chapter.total_raised
        %small.subtitle=@chapter.percentage_of_organization_funds
      %p
        %strong Total hours volunteered:
        %span.label.label-important=@chapter.sum_volunteerings
        %small.subtitle=@chapter.percentage_of_organization_hours
      %p
        %strong Legitimacy Ratio
        %span.label.label-warning=@chapter.chapter_legitimacy

  .row-fluid
    .span12.well
      %p
        %strong Per
        %strong=@chapter.member_type
      %p
        %strong Average Raised:
        %span.font-success=@chapter.average_donations
      %p
        %strong Hours Volunteered:
        %span.font-important=@chapter.average_volunteerings

  .row-fluid
    .span12.well
      %p
        %strong Location:
        %span=@chapter.school.location

      %p
        %strong Mission:
        %span=@chapter.mission

app/views/chapters/_chapter_users.html.haml
%tr
  -if current_user
    -if current_user.can_edit_chapter?(@chapter)
      -if @chapter.users.present?
        -UserDecorator.decorate_collection(@chapter.users).each do |user|
          %td
            %span.user-name=user.name
            %span.user-email=user.email
            %i.icon-envelope.show-email
            %i.icon-user.show-email
          %td=user.total_raised
          %td=user.total_hours
      -else
        %td.empty-table
          / %th.empty-table{colspan: 6}
          %span No users yet.
          %span=link_to "Invite or Import Some!", "#", :class => "btn btn-success btn-mini margin-sides-5"

app/views/chapters/_form.html.haml
=simple_form_for @chapter do |f|
  - if @chapter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chapter.errors.count, "error")} prohibited this chapter from being saved:"
      %ul
        - @chapter.errors.full_messages.each do |msg|
          %li= msg

  .field
    =f.text_field :name
  .field
    =f.text_field :location
  .field
    =f.text_area :mission
  .actions
    =f.button :submit

app/views/chapters/chapters_by_organization.js.erb
$(".dyn_dropdown").html('<%= options_for_select(@chapters.map {|o| [o.name, o.id]}).gsub(/n/, '') %>;');

app/views/chapters/edit.html.haml
.row-fluid.margin-top-50.text-center
  .span6.offset3.well
    %h3.inline Editing #{@chapter.name}
    =render 'form'
.row-fluid
  .span6.offset3.well.text-center
    =link_to raw('&larr; Back').html_safe, :back

app/views/chapters/index.html.haml
.row-fluid
  .span10.offset1.margin-top-25
    %h2.inline Chapter Roster
    %span.subtitle
      %small="(#{@chapters.size} total)"

    %span.pull-right.margin-top-25=link_to raw("&larr; Back").html_safe, :back, :class => "btn btn-mini"

    %table.table.table-bordered.table-striped
      %tr
        %th Funds Raised
        %th Volunteer Hours
        %th Chapter Name
        %th Location
        %th School
        %th Organization
        -if current_user
          -if current_user.has_role? :admin
            %th{colspan: 3} Manage

      -if @chapters
        -@chapters.each do |chapter|
          %tr
            %td= number_to_currency(chapter.donations.sum(:value))
            %td= chapter.volunteerings.sum(:hours)
            %td= link_to chapter.name, organization_chapter_path(chapter.organization, chapter)
            %td= chapter.school.location
            %td= link_to chapter.school.name, chapter.school
            %td= link_to chapter.organization.name, chapter.organization
            -if current_user
              -if current_user.has_role? :admin
                %td= link_to 'Edit', edit_chapter_path(chapter)
                %td= link_to 'Delete', chapter, :method => :delete, :data => { :confirm => 'Are you sure?' }


      -else
        No registered chapters yet. Email us to get going.

app/views/chapters/new.html.haml
%h1 New chapter

= render 'form'

= link_to 'Back', chapters_path

app/views/chapters/show.html.haml
.row-fluid
  .span10.offset1.margin-top-25

    %h2.inline=@chapter.name
    %span
      %small.subtitle Chapter

    =render "chapter_nav"

    .row-fluid
      =render "chapter_sidebar"
      =render "chapter_content"